import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import { cn } from '@/lib/utils'
import { fontMono } from '@/lib/font'

import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'

import { config } from '@/config'
import ContextProvider from '@/context'
import { ModalContextProvider } from '@/context/ModalContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <html lang="en">
      <body>
        <ModalContextProvider>
          <ContextProvider initialState={initialState}>
            {children}
          </ContextProvider>
        </ModalContextProvider>
      </body>
    </html>
  )
}
